export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'; // DONE - TODO: Errors
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'; // TODO: AJAX
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'; // DONE - TODO: Errors
export const DRAWING_UPLOAD_SUCCESS = 'DRAWING_UPLOAD_SUCCESS';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_OUT = 'LOG_OUT'; // DONE
