export const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS'; // DONE - TODO: Errors
export const STORE_REMEMBERED_USER = 'STORE_REMEMBERED_USER';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'; // DONE - TODO: Avatar + Errors
export const UPDATE_PHOTO_SUCCESS = 'UPDATE_PHOTO_SUCCESS'; // DONE - TODO: Avatar + Errors
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'; // DONE - TODO: Errors
export const DRAWING_UPLOAD_SUCCESS = 'DRAWING_UPLOAD_SUCCESS';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS'; // DONE - TODO: Errors
export const LOG_OUT_SUCCESS = 'LOG_OUT_SUCCESS'; // DONE - TODO: Errors
